language: cpp

compiler: gcc

dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libfftw3-dev python3 python3-pip
  - export OMP_NUM_THREADS=4

install:
  - pip3 install -r requirements.txt
  - make && make clean

script:
  - make test
